steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}', '.']
    dir: 'fastapi-app'
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}']
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['run', 'services', 'update', '${_SERVICE_NAME}', '--platform=managed', '--image=${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}', '--region=${_DEPLOY_REGION}', '--quiet']
    entrypoint: gcloud
    id: Deploy

  - name: 'python'
    entrypoint: 'bash'
    args: ['-c', 'pip install -r app/requirements.txt && pytest app/tests']
    dir: 'fastapi-app'
    id: Test

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'fastapi-service'
  _DEPLOY_REGION: 'us-central1'
  _AR_HOSTNAME: 'us-central1-docker.pkg.dev'
  _TRIGGER_ID: '7222b6ae-bb5a-4d87-bf35-1f9b52a56d77'
  _PLATFORM: 'managed'
